Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/BlockDelimiters:
  EnforcedStyle: always_braces

Style/DefWithParentheses:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MethodCallWithArgsParentheses:
  EnforcedStyle: omit_parentheses

Style/NestedParenthesizedCalls:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false